name: docker-build

on: 
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request_target:
    branches: ["main"]

env:
  IMAGE_NAME: ajeetraina/frontend
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Log into registry
        uses: docker/login-action@v3.0.0
        with:
          username: ajeetraina
          password: ${{ secrets.HUB_PAT }}
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        #with:
        #  version: "lab:latest"
        #  driver: cloud
        #  endpoint: "docker/ecosystem-bu"
        #  install: true

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
            com.docker.image.source.entrypoint=${{ env.DOCKERFILE_PATH }}

      - name: Build and push Docker image on push
        id: build-and-push
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64,linux/arm64"
          #attests: type=sbom,generator=docker/scout-sbom-indexer:1
          sbom: true
          provenance: true
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          
      - name: Analyze image
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@main
        with:
          command: cves
          image: registry://${{ steps.meta.outputs.tags }}
          platform: "linux/amd64"
          summary: true
          organization: ajeetraina

      - name: Build and push Docker image on PR
        id: build-and-push-pr
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64"
          sbom: false
          provenance: false
      
      - name: Policy to deployed image
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/scout-action@main
        with:
          command: policy
          image: local://${{ steps.meta.outputs.tags }}
          only-severities: critical,high
          to-env: prod
          platform: "linux/amd64"       
          summary: true
          organization: ajeetraina

      - name: Compare to deployed image
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/scout-action@main
        with:
          command: compare
          image: local://${{ steps.meta.outputs.tags }}
          only-severities: critical,high
          to-env: prod
          platform: "linux/amd64"       
          summary: true
          organization: ajeetraina  
          exit-code: true

    - name: Build
      on:
        push:
          branches:
            - main
        pull_request:
          types: [opened, synchronize, reopened]
     jobs:
       sonarcloud:
        name: SonarCloud
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
           with:
             fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
